#!/bin/bash 
alias zc="nvim ~/.zshrc"
alias tc="nvim ~/.config/alacritty/alacritty.yml"
alias ac="nvim ~/.config/awesome/rc.lua"
alias nc="nvim ~/.config/nvim/init.lua"

alias as="nvim ~/reinst/config/zsh/aliases.zsh"

alias la="exa -laghm@ --all --icons --color=always"
alias ll="exa -lghm@ --icons"

alias v="nvim"


# {{{ List

alias la='ls -a'
alias ll='ls -la'
alias l='ls'
alias l.="ls -A | egrep '^\.'"

# -------------------------------------------------------------------------- }}}
# {{{ Grep

# Colorize the grep command output for ease of use (good for log files).

alias grep='grep --color=auto'
alias egrep='egrep --color=auto'
alias fgrep='fgrep --color=auto'

# -------------------------------------------------------------------------- }}}
# {{{ Administrative aliases

# readable output
alias df='df -h'

# pacman unlock
# alias unlock="sudo rm /var/lib/pacman/db.lck"

# free
alias free="free -mt"

# use all cores
# alias uac="sh ~/.bin/main/000*"

# continue download
alias wget="wget -c"

#iso and version used to install ArcoLinux
# alias iso="cat /etc/dev-rel | awk -F '=' '/ISO/ {print $2}'"
# alias isoo="cat /etc/dev-rel"

# userlist
# alias userlist="cut -d: -f1 /etc/passwd"

# merge new settings
# alias merge="xrdb -merge ~/.Xresources"

# Aliases for software managment
# alias pacman='sudo pacman --color auto'
# alias update='sudo pacman -Syyu'

# paru and yay as aur helper - updates everything
# alias yallall="yay -Syu --noconfirm"
# alias paruall="paru -Syu --noconfirm"

# ps
alias psa="ps auxf"
# alias psgrep="ps aux | grep -v grep | grep -i -e VSZ -e"

# grub update
alias update-grub="sudo grub-mkconfig -o /boot/grub/grub.cfg"

#grub issue 08/2022
alias install-grub-efi="sudo grub-install --target=x86_64-efi --efi-directory=/boot/efi"

# add new fonts
alias update-fc='sudo fc-cache -fv'

# backup contents of /etc/skel to hidden backup folder in home/user
# alias bupskel='cp -Rf /etc/skel ~/.skel-backup-$(date +%Y.%m.%d-%H.%M.%S)'

# copy bashrc-latest over on bashrc - cb= copy bashrc
# alias cb='sudo cp /etc/skel/.bashrc ~/.bashrc && source ~/.bashrc'

# copy /etc/skel/.zshrc over on ~/.zshrc - cb= copy zshrc
# alias cz='sudo cp /etc/skel/.zshrc ~/.zshrc && source ~/.zshrc'

# switch between bash and zsh
alias tobash="sudo chsh $USER -s /usr/bin/bash && echo 'Now log out.'"
alias tozsh="sudo chsh $USER -s /usr/bin/zsh && echo 'Now log out.'"

#switch between lightdm and sddm
# alias tolightdm="sudo pacman -S lightdm lightdm-gtk-greeter lightdm-gtk-greeter-settings --noconfirm --needed ; sudo systemctl enable lightdm.service -f ; echo 'Lightm is active - reboot now'"
# alias tosddm="sudo pacman -S sddm --noconfirm --needed ; sudo systemctl enable sddm.service -f ; echo 'Sddm is active - reboot now'"
# alias toly="sudo pacman -S ly --noconfirm --needed ; sudo systemctl enable ly.service -f ; echo 'Ly is active - reboot now'"
# alias togdm="sudo pacman -S gdm --noconfirm --needed ; sudo systemctl enable gdm.service -f ; echo 'Gdm is active - reboot now'"
# alias tolxdm="sudo pacman -S lxdm --noconfirm --needed ; sudo systemctl enable lxdm.service -f ; echo 'Lxdm is active - reboot now'"

# quickly kill conkies
# alias kc='killall conky'

# quickly kill polybar
# alias kp='killall polybar'

# quickly kill picom
alias kpi='killall picom'

# hardware info --short
alias hw="hwinfo --short"

# skip integrity check
# alias yayskip='yay -S --mflags --skipinteg'
# alias trizenskip='trizen -S --skipinteg'

# check vulnerabilities microcode
# alias microcode='grep . /sys/devices/system/cpu/vulnerabilities/*'

# -------------------------------------------------------------------------- }}}
# {{{ Mirrors

# get fastest mirrors in your neighborhood
# alias mirror="sudo reflector -f 30 -l 30 --number 10 --verbose --save /etc/pacman.d/mirrorlist"
# alias mirrord="sudo reflector --latest 50 --number 20 --sort delay --save /etc/pacman.d/mirrorlist"
# alias mirrors="sudo reflector --latest 50 --number 20 --sort score --save /etc/pacman.d/mirrorlist"
# alias mirrora="sudo reflector --latest 50 --number 20 --sort age --save /etc/pacman.d/mirrorlist"

# -------------------------------------------------------------------------- }}}
# {{{ Virtual box

# mounting the folder Public for exchange between host and guest on virtualbox
# alias vbm="sudo mount -t vboxsf -o rw,uid=1000,gid=1000 Public /home/$USER/Public"

# -------------------------------------------------------------------------- }}}
# # {{{ shopt
#
# shopt -s autocd         # change to named directory
# shopt -s cdspell        # autocorrects cd misspellings
# shopt -s cmdhist        # save multi-line commands in history as single line
# shopt -s dotglob        # dot file names are included in path expansion.
# shopt -s histappend     # do not overwrite history
# shopt -s expand_aliases # expand aliases

# -------------------------------------------------------------------------- }}}
# {{{ Youtube

alias yta-aac="yt-dlp --extract-audio --audio-format aac "
alias yta-best="yt-dlp --extract-audio --audio-format best "
alias yta-flac="yt-dlp --extract-audio --audio-format flac "
alias yta-mp3="yt-dlp --extract-audio --audio-format mp3 "
alias ytv-best="yt-dlp -f 'bestvideo[ext=mp4]+bestaudio[ext=m4a]/bestvideo+bestaudio' --merge-output-format mp4 "

# -------------------------------------------------------------------------- }}}
# {{{ Packages

# Recent Installed Packages
alias rip="expac --timefmt='%Y-%m-%d %T' '%l\t%n %v' | sort | tail -200 | nl"
alias riplong="expac --timefmt='%Y-%m-%d %T' '%l\t%n %v' | sort | tail -3000 | nl"

# Cleanup orphaned packages
# alias cleanup='sudo pacman -Rns $(pacman -Qtdq)'

# -------------------------------------------------------------------------- }}}
# {{{ Job control

# get the error messages from journalctl
alias jctl="journalctl -p 3 -xb"

# -------------------------------------------------------------------------- }}}
# {{{ Important configuration files

# alias nconfgrub="sudo nvim /boot/grub/grub.cfg"
# alias ngrub="sudo nvim /etc/default/grub"
# alias nlightdm="sudo nvim /etc/lightdm/lightdm.conf"
# alias nmirrorlist="sudo nvim /etc/pacman.d/mirrorlist"
# alias nmkinitcpio="sudo nvim /etc/mkinitcpio.conf"
# alias noblogout="sudo nvim /etc/oblogout.conf"
# alias npacman="sudo nvim /etc/pacman.conf"
# alias nslim="sudo nvim /etc/slim.conf"

# -------------------------------------------------------------------------- }}}
# {{{ gpg

# verify signature for isos
# alias gpg-check="gpg2 --keyserver-options auto-key-retrieve --verify"

# receive the key of a developer
# alias gpg-retrieve="gpg2 --keyserver-options auto-key-retrieve --receive-keys"

# -------------------------------------------------------------------------- }}}
# {{{ shutdown or reboot or lock screen.

alias ssn="sudo shutdown now"
alias sr="sudo reboot"
# alias bls="betterlockscreen -u /usr/share/backgrounds/arcolinux/"





# {{{ Operating system specific settings.
# if osType "/darwin"; then
# 	alias la='ls -A'
# 	alias ll='ls -lahG'
# fi

# -------------------------------------------------------------------------- }}}
# {{{ Vim keybindings.

# set -o vi

# -------------------------------------------------------------------------- }}}
# {{{ latexrun is defined when present.

if fileExists $GITHOME/latexrun/latexrun; then
	alias latexrun='$GITHOME/latex/latexrun/latexrun'
fi

# -------------------------------------------------------------------------- }}}
# {{{ Tmux setup.

if fileExists /usr/bin/tmux; then
	alias tmux='tmux -2'
fi

# -------------------------------------------------------------------------- }}}
# {{{ Use bat and exa when they are installed.

if osType "msys"; then
	alias cat='bat -p'
	ls='ls --color=auto'
else
	[ -f /usr/bin/bat ] && alias cat='bat -p'
	[ -f /usr/bin/exa ] && alias ls='exa'
	[ ! -f /usr/bin/exa ] && alias ls='ls --color=auto'
fi

# -------------------------------------------------------------------------- }}}
# {{{ General purpose aliases.

alias cgits='clear && gits'
alias cls='clear'
alias encrypt='$BINHOME/encrypt'
if [[ $(rg --ignore-case '"Ubuntu' /etc/os-release -c 2>/dev/null) -gt 0 ]]; then
	alias fd='fdfind'
	alias fde='fdfind --no-ignore --extension'
else
	alias fde='fd --no-ignore --extension'
fi
alias fgrep='fgrep --color=auto'
alias ga='git add'
alias gP='git pull'
alias gbp='gits bb pull'
alias gc='git commit -m'
alias gco.='git checkout -- .'
alias ggp='gits git pull'
alias gl7='git logg -7'
alias glg='git log'
alias glgg='git logg'
alias glgi='git logi'
alias gp='git push'
alias grep='grep --color=auto'
alias grh='git reset HEAD'
alias gs='clear && git status'
alias gsuo='git push --set-upstream origin'
alias h='history'
alias help='man'
alias kax='sudo killall Xorg'
alias l1='ls -1'
alias lad='ls -lad .*'
alias las='find . -maxdepth 1 -type l -printf "%p -> %l\n" | sort'
alias lass='find . -type l -printf "%p -> %l\n" | sort'
alias lg='lvim +G'
alias l24='find . -newermt "-24 hours" -ls'
alias me='clear && exec bash'
alias mv='mv -v'
alias n='nvim'
alias nano='$EDITOR'
alias ng='nvim +G'
alias rbe='eval "$(rbenv init - n)"'
alias rbn='sudo reboot now'
alias rgits='repeat gits'
alias s='source'
alias sa='source $BASHHOME/my_aliases'
alias sde='sudoedit'
alias sdn='sudo shutdown now'
alias se='source $BASHHOME/my_exports'
alias sf='source $BASHHOME/my_functions'
alias slv='switchNeovim'
alias snv='switchNeovim'
alias sp='source $BASHHOME/my_paths'
alias ssh='ssh -A'
alias ta='tmux attach'
alias v='vim'
alias vg='vim +G'
alias vp='vim +PlugUpdate'
alias wlv='cat ~/.lunarvim_in_use_okay_to_delete'
alias wnv='cat ~/.neovim_in_use_okay_to_delete'
alias xz='$EDITOR -c "let g:tty='\''$(tty)'\''"'

# -------------------------------------------------------------------------- }}}
# {{{ Aliases to folders I visit frequently.

alias .a='cd $BASHHOME'
alias .b='cd $BINHOME'
alias .c='cd $CFGHOME'
alias .d='cd $DOTHOME'
alias .g='cd $GITHOME'
alias Cd='cd $GITHOME/color'
alias Dc='cd $HOME/Documents'
alias Dd='cd $HOME/Downloads'
alias Ld='cd $HOME/.local/share/nvim/lsp_servers'
alias ac='cd $GITHOME/AllanConsulting'
alias bd='cd $GITHOME/bootstrap'
alias gd='cd $GITHOME'
alias hh='cd $GITHOME/HowardHouse'
alias nd='cd $GITHOME/nvim.traap'
alias pd='cd $HOME/.local/share/nvim/site/pack/packer/start'
alias rd='cd $GITHOME/resume'
alias sd='cd $GITHOME/ssh'
alias td='cd $GITHOME/tmux'
alias vb='cd $GITHOME/vim/bundle'
alias vd='cd $GITHOME/vim'
alias wd='cd $GITHOME/wiki'
alias yd='cd $GITHOME/youtube'

alias cal='cd $CFGHOME/alacritty'
alias cbs='cd $CFGHOME/bspwm'
alias cdc='cd $CFGHOME/dconf'
alias cdu='cd $CFGHOME/dunst'
alias cki='cd $CFGHOME/kitty'
alias cnv='cd $CFGHOME/nvim'
alias cpi='cd $CFGHOME/picom'
alias cpo='cd $CFGHOME/polybar'
alias cra='cd $CFGHOME/ranger'
alias csx='cd $CFGHOME/sxhkd'
alias cth='cd $CFGHOME/Thunar'

# -------------------------------------------------------------------------- }}}
# {{{ Repeat command are used when I enable my resume editor.

alias rgl='repeat git logg -6'
alias rgs='repeat git status --short'

# -------------------------------------------------------------------------- }}}
# {{{ Perforce defaults.

# if osType "linux"; then
# 	if hostName "Ryder"; then
# 		alias p4='${P4DISK}/2013.1/p4'
# 		alias p4d='${P4DISK}/2013.1/p4d'
# 	fi
# fi

# -------------------------------------------------------------------------- }}}
# {{{ File I edit frequently.  These aliases mirror keybinds used in Vim.

alias ,eb='$EDITOR $BASHHOME/bootstrap.vim'
alias ,ec='$EDITOR $GITHOME/ssh/config.vim'
alias ,ed='$EDITOR $GITHOME/vim/custom-dictionary.utf-8.add'
alias ,eg='$EDITOR $GITHOME/ssh/gitconfig'
alias ,en='$EDITOR $GITHOME/nvim.traap/init.lua'
alias ,ep='$EDITOR $GITHOME/nvim.traap/lua/traap/plugins/init.lua'
alias ,em='$EDITOR $GITHOME/vim/minimal-plug.vim'
alias ,et='$EDITOR $GITHOME/tmux/tmux.conf'
alias ,ev='$EDITOR $GITHOME/vim/vimrc'

alias ,ma='$EDITOR $BASHHOME/my_aliases'
alias ,mb='$EDITOR $BASHHOME/bashrc'
alias ,mc='$EDITOR $BASHHOME/my_completions'
alias ,me='$EDITOR $BASHHOME/my_exports'
alias ,mf='$EDITOR $BASHHOME/my_functions'
alias ,mp='$EDITOR $BASHHOME/my_paths'
alias ,mt='$EDITOR $BASHHOME/my_prompt'
alias ,mz='$EDITOR $BASHHOME/bashrc-personal'

alias ,xb='$EDITOR $BASHHOME/bspwmrc'
alias ,xs='$EDITOR $BASHHOME/sxhkdrc'

# -------------------------------------------------------------------------- }}}
# {{{ tmux sessions I frequently use.

alias tao='ao ao'
alias tbash='ao bash'
alias tkjv='ao kjv'
alias tnvim='ao nvim'
alias tsoup='ao soup'
alias tvim='ao vim'
alias tssh='ao ssh'
alias td='ao d'
alias th='ao h'
alias tt='ao t'
alias twiki='ao wiki'
alias tyt='ao youtube'

alias kao='tmux kill-session -t ao'
alias kbash='tmux kill-session -t bash'
alias kkjv='tmux kill-session -t kjv'
alias knvim='tmux kill-session -t nvim'
alias ksoup='tmux kill-session -t soup'
alias kssh='tmux kill-session -t ssh'
alias kd='tmux kill-session -t d'
alias kh='tmux kill-session -t h'
alias kt='tmux kill-session -t t'
alias kvim='tmux kill-session -t vim'
alias kwiki='tmux kill-session -t wiki'
alias kyt='tmux kill-session -t youtube'

# -------------------------------------------------------------------------- }}}
# {{{ archlinux tlmgr (texlive manager)

# export TEXMFDIST='/usr/share/texmf-dist'
# alias tlmgr='${TEXMFDIST}/scripts/texlive/tlmgr.pl --usermode'

# -------------------------------------------------------------------------- }}}
# {{{ WSL (Windows Subsystem for Linux)

# Windows paths are appended to PATH when WSL is present.

# if [[ -n $WSL_DISTRO_NAME ]]; then
# 	alias wsl=wsl.exe
# fi

# -------------------------------------------------------------------------- }}}





# Aliases
alias ..="cd ../"
alias ...="cd ../../"
alias ....="cd ../../../"
alias .....="cd ../../../../"
alias 7zc="7z a -mx=9"
alias acp="advcp -gv"
alias amv="advmv -gv"
alias apti="sudo apt install"
alias apts="apt search"
alias aptr="sudo apt remove"
alias aptq="apt show"
alias aptu="sudo apt update && sudo apt upgrade"
alias aran="autorandr -l"
alias asc="asciinema"
alias brc="brew cleanup"
alias bri="brew install"
alias brl="brew list"
alias brr="brew uninstall"
alias bru="brew upgrade"
alias cat="bat"
alias ccp="clipcopy"
alias cdx='cd $(xplr)'
alias cless='colorize_less -N'
alias cols='spectrum_ls'
alias cp="cp -irv"
alias cpa="clippaste"
alias diff="diff --color=auto"
alias e='nvim $(files)'
alias emd='emacs --daemon &'
alias emc="emacsclient -c -a 'emacs'"
alias emt='emacs --no-window-system'
alias exag="exa -ahlT -L=1  -s=extension --git --group-directories-first"
alias exdo='exercism download --exercise=hello-world --track=ruby'
alias exsu='exercism submit'
alias fd="fd -H"
alias fdir="find . -type d -name"
alias ffil="find . -type f -name"
alias files="fzf --preview 'bat --color=always --style=numbers --line-range=:500 {}'"
alias g="git"
alias ga="git add"
alias gc="git commit -m"
alias gl="git pull --rebase --autostash"
alias gp="git push"
alias gss="git status -s"
alias gbrr="git for-each-ref --count=30 --sort=-committerdate refs/heads/ --format='%(refname:short)'"
alias gcm='git checkout $(git_main_branch)'
alias gcma="git commit --amend -m"
alias gcman="git commit --amend --no-edit"
alias gcmn="git add . && git commit --amend --no-edit"
alias gdh="git diff HEAD"
alias gg="lazygit"
alias ghpc="gh pr create"
alias ghrc="gh repo clone"
alias ghrd="gh repo edit -d"
alias ghrh="gh repo edit -h"
alias ghrr="gh repo rename"
alias ghrs="gh release create"
alias ghrt="gh repo edit --add-topic "
alias ghrv="gh repo edit --visibility "
alias gmv="git mv"
alias gmx="git merge -X ours"
alias gsv="git status -v"
alias gtop='cd "$(git rev-parse --show-toplevel)"'
alias grep="grep --color=auto"
alias icat="kitty +kitten icat"
alias java8="export JAVA_HOME=/usr/lib/jvm/java-8-openjdk/jre"
alias java11="export JAVA_HOME=/usr/lib/jvm/java-11-openjdk/"
alias jupn="jupyter notebook"
# alias la="ls -AXb --group-directories-first --sort=extension"
alias la="lsd -A --group-dirs first --classify"
alias ldir="ls -d */"
alias litu="sudo light -A 10"
alias litd="sudo light -U 10"
alias ln="ln -sfnv"
alias loca="$EDITOR ~/.local.sh"
alias logout="sudo pkill -u \$USER"
alias ls='ls --color=auto'
alias lsda="lsd -A --group-dirs first --classify"
alias lsdo="lsd -A --group-dirs first --classify --recursive --depth=2"
alias me="README.md"
alias mv="mv -iv"
alias ncdu="ncdu --color=dark -x"
alias npi="npm install"
alias npr="npm run"
alias open="open_command"
alias paci="sudo pacman -S"
alias pacq="pacman -Qi"
alias pacr="sudo pacman -Rsc"
# alias pacrd="pacr $(pacman -Qdtq | tr '\n' ' ')"
alias pacs="pacman -Ss"
alias pacu="sudo pacman -Syu"
alias plasmar="kquitapp5 plasmashell && kstart5 plasmashell"
alias pp="prettyping --nolegend"
alias q="exit"
alias rm="rm -irv"
alias rmf="rm -rf"
# alias serv="python -m http.server 1234"
alias scr="scrot -cd 3 -F ~/Pictures/Screenshots/snap-%Y-%m-%d.png"
alias scrw="scrot -u -bcd 3 -F ~/Pictures/Screenshots/snap-%Y-%m-%d.png"
alias scrs="scrot -s -l width=3,color='#1688f0',mode=edge,opacity=90 -F ~/Pictures/Screenshots/snap-%Y-%m-%d.png"
alias serv="npx live-server --port=1234 ."
alias shad="ssh-add ~/.ssh/id_rsa"
alias shag='eval "$(ssh-agent -s)"'
alias sto="stackoverflow"
alias sysd="sudo systemctl disable"
alias syse="sudo systemctl enable"
alias sysr="sudo systemctl restart"
alias syss="systemctl status"
alias systa="sudo systemctl start"
alias systo="sudo systemctl stop"
alias tmux="tmux -u"
alias tmuxm="tmux new-session \; split-window -h \; split-window -v \; attach"
alias todo='nvim +"Telekasten goto_today"'
alias trii="trizen -S --noedit"
alias tris="trizen -Ss --noedit"
alias triu="trizen -Syu --noedit"
alias vi="nvim"
alias volu="amixer sset 'Master' 10%+"
alias vold="amixer sset 'Master' 10%-"
alias wifi="nmtui"
alias xp="xplr"
alias yayi="yay -S"
alias yayu="yay -Syu"
alias ytdl="youtube-dl"

if [ -f "/usr/bin/grc" ]; then
    alias df="grc df"
    alias gcc="grc gcc"
    alias iwconfig="grc iwconfig"
    alias last="grc last"
    alias make="grc make"
    alias mount="grc mount"
    alias mtr="grc mtr"
    alias ping="grc ping"
    alias ps="grc ps"
    alias traceroute="grc traceroute"
    alias wdiff="grc wdiff"
fi

alias vimrc="vim ~/.vimrc"
alias nvimrc="nvim ~/.config/nvim/init.lua"
alias zshrc="$EDITOR ~/.zshrc"
alias bashrc="$EDITOR ~/.bashrc"
alias alia="$EDITOR ~/.config/shell/aliases.sh"
alias enva="$EDITOR ~/.config/shell/envars.sh"
alias func="$EDITOR ~/.config/shell/functions.sh"
alias meow="$EDITOR ~/.config/kitty/kitty.conf"
alias p2k="$EDITOR ~/.config/shell/powerlevel2k.zsh"

# Causes Issues
# if [ -f "/usr/bin/kdeconnect-cli" ]; then
#     alias send="kdeconnect-cli -d "$(kdeconnect-cli -a --id-only)" --share"
# fi

