#!/bin/bash

# {{{ Linux only machines.

# NOTE: When order matters:  PrependToPath (beginn) and appendToPath (end).

# Programming languages.
prependToPath "$HOME"/.cargo/bin

# Ruby Environment Manager
if programExists rbenv; then
	eval "$(rbenv init - n)"
fi

# prependToPath only prepends to the path when the directory exists.
prependToPath "$HOME"/bin
prependToPath "$HOME"/.bin
prependToPath "$HOME"/.local/bin
appendToPath "$HOME"/.local/share/nvim/mason/bin
appendToPath "$BASHHOME"/bin

prependToPath "$HOME"/.npm/bin
prependToPath "$HOME"/.luarocks/bin

appendToPath "$HOME"/.local/share/bob/nvim-bin

# -------------------------------------------------------------------------- }}}
