#!/bin/sh

# history
HISTFILE=~/.zsh_history

# Define directory exports that my_functions use.
# BBHOME=$HOME/bb
# export BBHOME

CFGHOME=$HOME/.config
export CFGHOME

GITHOME=$HOME/git
export GITHOME

GITPATH=$GITHOME
export GITPATH

DOTHOME=$GITHOME/reinst
export DOTHOME

BASHHOME=$DOTHOME/config/bash
export BASHHOME

BINHOME=$BASHHOME/bin
export BINHOME

# SSHHOME=$GITHOME/ssh
# export SSHHOME
#
# WIKIHOME=$GITHOME/wiki
# export WIKIHOME
 
# {{{ Customize my shell. Array order matters.

my_array=("functions" "exports" "aliases" "paths")

for m in "${my_array[@]}"; do
	[[ -f "$BASHHOME/my_$m" ]] && source "$BASHHOME/my_$m"
done

# Load my keys.
# sshkeys

# -------------------------------------------------------------------------- }}}

#set -o vi
# bindkey '^ ' autosuggest-accept
bindkey '^A' beginning-of-line
bindkey '^E' end-of-line

# source .zshrc-personal

export NVM_DIR="$HOME/.config/nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion



## Приглашение
autoload -U colors && colors
# export PROMPT='%n*%m> ' export RPROMPT='[%~]'
PROMPT="%{$fg[red]%}%n%{$reset_color%}*%{$fg[blue]%}%m%{$fg_no_bold[yellow]%}> "
RPROMPT="[%{$fg_no_bold[yellow]%}%~]"


## plugins
source ~/.local/share/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
