#!bin/bash
# {{{ Stooges: Honoring Larry, Moe, and Curley ... Nyuk, nyuk, nyuk.
#
# Bash scripting cheatsheet => https://devhints.io/bash

echo ${HOST} "on" ${OSTYPE}

# -------------------------------------------------------------------------- }}}
# {{{ Disable ctrl-s and ctrl-q

stty -ixon

# -------------------------------------------------------------------------- }}}
# {{{ Infanite history

HISTSIZE= HISTFILESIZE=

# -------------------------------------------------------------------------- }}}
# {{{ ArchLinux specific keyboard setting.

# # Turn off numlock and swap Cap Lock && Escape keys on Arch Linux
# if [[ $(uname -r) =~ 'arch' || $(uname -r) =~ 'lts' ]]; then
#   numlockx off
#   if [[ $(lspci -nn | rg VGA -c) == 1 ]]; then
#     setxkbmap -option caps:swapescape
#   fi
# fi

# -------------------------------------------------------------------------- }}}
# Define directory exports that my_functions use.
# BBHOME=$HOME/bb
# export BBHOME

CFGHOME=$HOME/.config
export CFGHOME

GITHOME=$HOME/git
export GITHOME

GITPATH=$GITHOME
export GITPATH

DOTHOME=$GITHOME/reinst
export DOTHOME

BASHHOME=$DOTHOME/config/bash
export BASHHOME

BINHOME=$BASHHOME/bin
export BINHOME

# SSHHOME=$GITHOME/ssh
# export SSHHOME
#
# WIKIHOME=$GITHOME/wiki
# export WIKIHOME
 
# {{{ Customize my bash experience.

# Define functions and paths for this shell.
dofile=${HOME}/git/reinst/config/bash

# Customize my shell.
my_array=("functions" "exports" "aliases" "paths")
for m in ${my_array[@]}; do
  x=$dofile/my_$m
  source $x
done

# -------------------------------------------------------------------------- }}}
